version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum â€œpackage.jsonâ€ }}
      - run: npm test
      - run: npm run build
          name: Creating Artifacts
          command: |
            echo dist/bundle.js > artifact-1;
            mkdir art;
            echo "my artifact files in a dir" > art/artifact-2;

      - store_test_results:
          path: test/test-results
      - store_artifacts:
          path: art/artifact-1
      - store_artifacts:
          path: art/artifacts
